config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  get 'simple_pages/delivery'
  get 'simple_pages/order'
  get 'simple_pages/faq'
  resources :perfumes
  root 'simple_pages#index'
  get 'simple_pages/index'
  post 'simple_pages/thank_you'
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.admin?
      can :manage, :all
  else
      can [:show, :index], Perfume
  end
end

    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/perfume.rb
class Perfume < ApplicationRecord

	def self.search(search_term)
		if Rails.env.production?
			Perfume.where("brand ilike ? OR title ilike ?", "%#{search_term}%", "%#{search_term}%")
		else
			Perfume.where("brand LIKE ? OR title LIKE ?", "%#{search_term}%", "%#{search_term}%")
		end
	end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	rescue_from CanCan::AccessDenied do |exception|
  	redirect_to main_app.root_url, alert: exception.message
	end

end

app/controllers/perfumes_controller.rb
class PerfumesController < ApplicationController
  before_action :set_perfume, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  load_and_authorize_resource only: [:new, :edit, :update, :destroy]

  # GET /perfumes
  # GET /perfumes.json
  def index
    if params[:q]
      search_term = params[:q]
      @perfumes = Perfume.search(search_term).paginate(page: params[:page])
    else
      @perfumes = Perfume.paginate(page: params[:page], per_page: 16)
    end
  end

  # GET /perfumes/1
  # GET /perfumes/1.json
  def show
  end

  # GET /perfumes/new
  def new
    @perfume = Perfume.new
  end

  # GET /perfumes/1/edit
  def edit
  end

  # POST /perfumes
  # POST /perfumes.json
  def create
    @perfume = Perfume.new(perfume_params)

    respond_to do |format|
      if @perfume.save
        format.html { redirect_to @perfume, notice: 'Perfume was successfully created.' }
        format.json { render :show, status: :created, location: @perfume }
      else
        format.html { render :new }
        format.json { render json: @perfume.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /perfumes/1
  # PATCH/PUT /perfumes/1.json
  def update
    respond_to do |format|
      if @perfume.update(perfume_params)
        format.html { redirect_to @perfume, notice: 'Perfume was successfully updated.' }
        format.json { render :show, status: :ok, location: @perfume }
      else
        format.html { render :edit }
        format.json { render json: @perfume.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /perfumes/1
  # DELETE /perfumes/1.json
  def destroy
    @perfume.destroy
    respond_to do |format|
      format.html { redirect_to perfumes_url, notice: 'Perfume was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_perfume
      @perfume = Perfume.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def perfume_params
      params.require(:perfume).permit(:img, :brand, :title, :gender, :volume, :price, :description)
    end
end

app/controllers/simple_pages_controller.rb
class SimplePagesController < ApplicationController
  def delivery
  end

  def order
  end

  def faq
  end

  def thank_you
  	@name = params[:name]
  	@email = params[:email]
  	@contact_number = params[:contact_number]
  	@message = params[:message]
  	ActionMailer::Base.mail(from: @email,
  														to: "peacockperfumes@gmail.com",
  											 subject: "A new email from #{@name}, contact number #{@contact_number}",
  											 		body: @message).deliver_now
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/perfumes_helper.rb
module PerfumesHelper
end

app/helpers/simple_pages_helper.rb
module SimplePagesHelper
end

app/views/layouts/_footer.html.erb
<footer> 
  <div class="container padding-top">
    <div class="row">
      <div class="col-xs-6 col-sm-4">
        <p class="lead text-white">Disclaimer</p>
        <p class="small text-muted">These are proper alcohol based perfumes (Not Water or Oil based) which are boxed and sealed in the same packaging as the originals. They look and smell like the authentic perfume you know and love <span class="text-bold">(They just don’t last as long).</span> Please note that these are NOT original perfumes, they are AAA grade REPLICAS imported from Dubai. In certain cases, a little defect may be present on the product itself, however, some perfumes are 100% perfect where you would find no mistakes. Quality of packaging may differ.</p>
      </div>
      <div class="col-xs-6 col-sm-4">
        <p class="lead text-white">Terms and Conditions</p>
        <p class="small text-muted">By placing an order & paying for the order, you are offering to purchase the product subject to the following terms and conditions. All orders are subject to availability and confirmation of the order price. Scent me Fragrances retains the right to refuse any request made by you, and by no means can this Terms & Conditions be changed without the consent of the owner. <span class="text-bold">No claims made on products and no false promises. To be ordered and bought at one’s own discretion and choice.</span> Terms & Conditions Apply…</p>
      </div>
      <div class="col-xs-6 col-sm-4">
        <p class="lead text-white">Refunds</p>
        <p class="small text-muted">Due to the nature of our products we regret no returns, refunds or exchanges are accepted and no warranties are offered on any items. Please note that once your order has been processed, it may not be cancelled.</p>
      </div>
    </div>
  </div>
  <div class="text-center copyright">
    <p class="small my-auto">&copy; Copyright 2019, Peacock Perfumes | All Rights Reserved.</p>
  </div>
</footer>

app/views/layouts/_header.html.erb
  <head>
    
    <title>Peacock Perfumes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Favicon -->
    <%= favicon_link_tag "favicon.ico" %>

    <!-- Fontawesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

    <!-- Custom Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Tangerine|Alegreya+SC" rel="stylesheet">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- Custom Style Sheets -->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <!-- Custom javaScript -->
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Bootstrap jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <meta name="viewport" content="width=device-width, initial-scale=1">

  </head>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-content" aria-controls="navbar-content" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse justify-content-center" id="navbar-content">
    <ul class="navbar-nav">
      <li class="nav-item my-auto mx-auto">
        <%= link_to "Perfumes", perfumes_path, class: 'nav-link' %>
      </li>
      <li class="nav-item my-auto mx-auto">
        <%= link_to "Order", simple_pages_order_path, class: 'nav-link' %>
      </li>
      <li class="nav-item mx-auto">
        <%= link_to image_tag("peacock-brand-image.png", size: '130x155'), root_path, class: 'navbar-brand' %>
      </li>
      <li class="nav-item my-auto mx-auto">
        <%= link_to "Delivery", simple_pages_delivery_path, class: 'nav-link' %>
      </li>
      <li class="nav-item my-auto mx-auto">
        <%= link_to "FAQ", simple_pages_faq_path, class: 'nav-link' %>
      </li>
      <% if user_signed_in? %>
      <li class="nav-item my-auto mx-auto">
        <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "nav-link") %>
      </li>
      <% end -%>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<%= render 'layouts/header' %>

<body>
  
  <%= render 'layouts/nav' %>


  <% if notice %>
  <p id="notice" class="alert alert-primary"><%= notice %></p>
  <% end %>
  <% if alert %>
  <p id="alert" class="alert alert-warning"><%= alert %></p>
  <% end %>


  <div class="container-fluid main-container">
    <%= yield %>
  </div>

  <%= render 'layouts/footer' %>

</body>
</html>

app/views/perfumes/_form.html.erb
<%= form_with(model: perfume, local: true) do |form| %>
  <% if perfume.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(perfume.errors.count, "error") %> prohibited this perfume from being saved:</h2>

      <ul>
      <% perfume.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :img %>
    <%= form.text_field :img %>
  </div>

  <div class="field">
    <%= form.label :brand %>
    <%= form.text_field :brand %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :gender %>
    <%= form.text_field :gender %>
  </div>

  <div class="field">
    <%= form.label :volume %>
    <%= form.number_field :volume %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/perfumes/edit.html.erb
<h1>Editing Perfume</h1>

<%= render 'form', perfume: @perfume %>

<%= link_to 'Show', @perfume %> |
<%= link_to 'Back', perfumes_path %>

app/views/perfumes/index.html.erb
<div class="container padding-top">
  <div class="text-center">
    <h1 class="display-4">Perfumes</h1>
    <h5>Free delivery on orders exceeding R400</h5>
    <h6>R90 Delivery fee for orders under R400</h6>
  </div>

  <hr>

  <%= form_with(url: perfumes_path, method: 'get', local: true, class: 'form-control-sm', id: 'form-search') do |form| %>
  <div class="row justify-content-center">
    <%= form.label :q, 'Search for:', class: 'sr-only' %>
    <%= form.text_field :q, id: 'q', value: params[:q] %>
    <%= form.submit "Search" %>

  </div>
  <% end -%>

  <div class="row">
    <% @perfumes.each do |perfume| %>
    <div class="col-xs-6 col-sm-4 col-md-3">
      <%= link_to perfume, { class: 'text-decoration-none' } do %>
      <div class="text-center perfume-container">
        <%= image_tag perfume.img, class: 'img-fluid', size: '100x100' %>
        <div class="perfume-container-text">
          <h6 class="brand font-weight-bold"><%= perfume.brand %></h6>
          <h6><%= perfume.title %></h6>
          <p class="text-muted"><%= perfume.volume %>ml - <%= perfume.gender %></p>
          <!-- <p class="perfume-price">R<%#= perfume.price %></p> -->
          <% if user_signed_in? && current_user.admin? %>
          <%= link_to 'Show', perfume %>
          <%= link_to 'Edit', edit_perfume_path(perfume) %>
          <%= link_to 'Destroy', perfume, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end -%>
        </div>
      </div>
      <% end -%>
      <hr>
    </div>
    <% end -%>
  </div>
</div>

<%= will_paginate @perfumes, class: 'apple_pagination' %>

<br>

<% if user_signed_in? && current_user.admin? %>
<%= link_to 'New Perfume', new_perfume_path %>
<% end -%>

app/views/perfumes/new.html.erb
<h1>New Perfume</h1>

<%= render 'form', perfume: @perfume %>

<%= link_to 'Back', perfumes_path %>

app/views/perfumes/show.html.erb
<div class="container padding-top">
  <div class="row">
    <div class="col-xs-12 col-sm-6">
      <div class="perfume-show-image">
        <%= image_tag @perfume.img, class: 'img-fluid mx-auto perfume-show', size: '300x400' %>
      </div>
    </div>
    <div class="col-xs-12 col-sm-6">
      <div class="perfume-info">
        <h4><%= @perfume.brand %> | <%= @perfume.title %></h4>
        <p class="text-muted small"><%= @perfume.gender %></p>
        <!-- <h6 class="text-bold">R<%#= @perfume.price %></h6> -->
        <hr>
        <h6 class="text-bold">SIZE: <%= @perfume.volume %>ml</h6>
        <br>
        <div class="perfume-info-container">
          <p class="perfume-show-information"><i class="fas fa-info-circle"></i>  Details</p>
        </div>
        <p><%= @perfume.description %></p>
        <%= link_to "BACK", perfumes_path, class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
</div>
<br>

app/views/simple_pages/delivery.html.erb
<div class="container padding-top">
  <div class="text-center">
    <h1 class="display-4">Delivery</h1>
    <h5>Free delivery on orders exceeding R400</h5>
    <h6>R90 Delivery fee for orders under R400</h6>
  </div>
  <hr>

  <p class="lead">
    Our goal is to offer you free shipping with ease of mind, knowing your product is on its way to you.
  </p>
  <p>
     We offer free shipping services (on orders exceeding R400), no matter where in South Africa you live. Every day we deliver to numerous customers, so ensuring that we provide the very highest levels of responsiveness to you at all times, is of the utmost importance to us.
  </p>
  <p class="lead">
    The time frame for order delivery is divided into two parts:
  </p>
  <p><span class="text-bold">Processing time: </span>
    Order verification, tailoring, quality check and packaging. All orders are sent for dispatch within 48 hours after the order is placed. Processing orders for shipment may take another 1 - 2.
  </p>
  <p><span class="text-bold">Shipping time:</span>
   This refers to the time it takes for items to be shipped from our warehouse to the destination. Shipping times varies from city to city.</p>
   <p>Major cities are usually 1 - 2 days.</p>
   <p>Rural Areas are usually 3 - 5 days.</p>
</div>

app/views/simple_pages/faq.html.erb
<div class="container padding-top">
  <div class="text-center">
    <h1 class="display-4">Frequently Asked Questions</h1>
    <h5>If you have any questions do not hesitate to contact us</h5>
  </div>
  <hr>

  <div id="accordion">

    <div class="card">
      <div class="card-header">
        <a href="#faq1" class="card-link" data-toggle="collapse">
          Why does perfume smell different on different people?
        </a>
      </div>
      <div id="faq1" class="collapse show" data-parent="#accordian">
        <div class="card-body">
          <p class="text-muted small">Your own body chemistry affects how different notes react on your skin. Anything that affects the “natural” smell of your skin, such as stress, hormonal changes, your current diet or medications, might change how a perfume smells on you.</p>
        </div>
      </div>
    </div>
    <div class="card">
      <div class="card-header">
        <a href="#faq2" class="card-link" data-toggle="collapse">
          Why do I see people selling these as originals on original rejects?
        </a>
      </div>
      <div id="faq2" class="collapse" data-parent="#accordian">
        <div class="card-body">
          <span class="text-bold small text-muted">Honesty is the Best Policy</span><span class="small text-muted"> – Please note that there is only one shipment coming into South Africa. You might see allot of ads and people selling these perfumes claiming they are either original or only original rejects. *(This is all false information)* It is so easy to mislead someone, as these perfumes are boxed, sealed, barcoded and packaged exactly like the original and not many people know the actual facts about original rejected stock. Just as anything in life, you can’t expect something to be original with such a hugely discounted price. (If it seems too good to be true, it is).</span>

          <p class="text-muted small">You would also see that these people who are selling them as originals or original rejected stock all claim the same thing, they don’t last as long, a small defect might sometimes appear on some items, it will be boxed and sealed and it’s all mainly imported, that is because; what they are selling are the exact same perfume as these, coming from the same shipment.</p>

          <p class="text-muted small">If you do just a little research on this subject, you will very quickly learn that original rejected perfume will never come in a box and especially not sealed. If you are ever unsure if someone is ever selling a real original reject, first ask if it comes in a box or not…</p>

          <p class="text-bold text-muted small">IN SHORT:</p>

          <p class="text-underlined text-muted small">100% Original Reject Perfume</p>
          
          <ul>
            <li class="text-muted small">Will have some defects on bottle/label, caps etc.</li>
            <li class="text-muted small">Liquid inside will be 100% original.</li>
            <li class="text-muted small">The perfumes come without the packaging box.</li>
            <li class="text-muted small">If you see it being advertised as AAA Grade, it’s NOT an original reject.</li>
          </ul>
        </div>
      </div>
    </div>
    <div class="card">
      <div class="card-header">
        <a href="#faq3" class="card-link" data-toggle="collapse">
          What payment methods do you accept?
        </a>
      </div>
      <div id="faq3" class="collapse" data-parent="#accordian">
        <div class="card-body">
          <p class="text-muted small">We accept only EFT payments.</p>
          <p class="text-muted small">COD is not accepted as there is no way that the courier will first ask for cash before they deliver and then send that back to us.</p>
      </div>
    </div>
    <div class="card">
      <div class="card-header">
        <a href="#faq4" class="card-link" data-toggle="collapse">
          How long does the smell last?
        </a>
      </div>
      <div id="faq4" class="collapse" data-parent="#accordian">
        <div class="card-body">
          <p class="small text-bold text-muted">This is a hard question.</p>

          <p class="text-muted small"><span class="text-bold">First:</span> It’s very important to note that these perfumes DOES NOT last as long as the original in store would. If you are used to the original and you can spend the amounts charged for the originals please don’t buy these at this price and expect the lasting power of the ones in store.</p>

          <p class="text-muted small"><span class="text-bold">Second:</span> Every single perfume is different and cannot be expected to have the same lasting power as some scents are meant to be lighter and some heavier. For example: Dolce & Gabbana Light Blue EDT is designed to be a lighter fragrance than Tom Ford’s Black Orchid.</p>

          <p class="text-muted small"><span class="text-bold">Third:</span> Your skin & diet plays a huge roll. We have had clients who bought the same perfume but the one said it lasts up to 7-8 hours on her skin, where the other said 30 minutes. Another example is: Some people tested the ORIGINALS and it didn’t even last 20 minutes before it was completely gone. It really depends from person to person.</p>

          <p class="text-muted small"><small class="text-bold">Fourth:</small> Heat maximizes perfume. Your neck, wrists, backs of knees, and other pulse points emit more heat than other parts of your body. And that heat actually activates and maximizes your perfume. There are times during the day where perfume might smell stronger than other times because of heat.</p>
        </div>
      </div>
    </div>
    <div class="card">
      <div class="card-header">
        <a href="#faq5" class="card-link" data-toggle="collapse">
          How do I track my order?
        </a>
      </div>
      <div id="faq5" class="collapse" data-parent="#accordian">
        <div class="card-body">
          <p class="text-muted small">We will contact you with a message containing the Courier Tracking Number for your order, along with the courier website details.</p>
        </div>
      </div>
    </div>
    <div class="card">
      <div class="card-header">
        <a href="#faq6" class="card-link" data-toggle="collapse">
          Do you have Testers?
        </a>
      </div>
      <div id="faq6" class="collapse" data-parent="#accordian">
        <div class="card-body">
          <p class="text-muted small">Unfortunately these perfumes does not have 5ml testers. These are not the Oil based perfumes that people mix at home, pour into 5ml, 30 ml, 50 ml, and 100ml glass bottles and then distribute. These perfumes are mainly imported and the manufacturer does not make 5ml testers.</p>
          <p class="text-muted small">If you go to Edgars/Dischem etc. you will see that they also do not have or use any 5ml testers but use the actual bottle as you would buy it as a tester.</p>
        </div>
      </div>
    </div>
    
  </div> <!-- end #accordion -->

</div> <!-- end .container -->

app/views/simple_pages/index.html.erb
<div id="landing-carousel" class="carousel slide" data-ride="carousel" data-pause="false" data-interval="4000">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%= image_tag "carousel-1.jpeg", class: 'd-block w-100' %>
    </div>
    <div class="carousel-item">
      <%= image_tag "carousel-2.jpeg", class: 'd-block w-100' %>
    </div>
    <div class="carousel-item">
      <%= image_tag "carousel-3.jpeg", class: 'd-block w-100' %>
    </div>
    <div class="carousel-item">
      <%= image_tag "carousel-4.jpeg", class: 'd-block w-100' %>
    </div>
    <div class="carousel-item">
      <%= image_tag "carousel-5.jpeg", class: 'd-block w-100' %>
    </div>
  </div>
</div>

app/views/simple_pages/order.html.erb
<div class="container padding-top">
  <div class="text-center">
    <h1 class="display-4">Ordering</h1>
    <h5>Free delivery on orders exceeding R400</h5>
    <h6>R90 Delivery fee for orders under R400</h6>
  </div>
  <hr>

  <%= flash[:notice] %>

  <%= form_with(url:"/simple_pages/thank_you", class: "form-contact mx-auto was-validated", method: "post", local: true) do |form| %>

    <div class="form-group">
      <%= form.label :name, class: 'sr-only' %>
      <%= form.text_field :name, class: 'form-control', placeholder: "Enter Name", required: true %>
      <div class="valid-feedback">Valid.</div>
      <div class="invalid-feedback">Please fill out this field.</div>
    </div>

    <div class="form-group">
      <%= form.label :email, class: 'sr-only' %>
      <%= form.text_field :email, class: 'form-control', placeholder: "Enter Email", type: :email, required: true %>
      <div class="valid-feedback">Valid.</div>
      <div class="invalid-feedback">Please fill out this field.</div>
    </div>

    <div class="form-group">
      <%= form.label :contact_number, class: 'sr-only' %>
      <%= form.text_field :contact_number, class: 'form-control', placeholder: "Cellphone Number", type: :tel, pattern: '^\d{10}$', required: true %>
      <div class="valid-feedback">Valid.</div>
      <div class="invalid-feedback">Please fill out this field.</div>
    </div>

    <div class="form-group">
      <%= form.label :message, class: 'sr-only' %>
      <%= form.text_area :message, class: 'form-control', placeholder: "Enter Message", rows: 5, required: true %>
    </div>

    <%= form.submit "Send", class: 'form_label' %>
    <% end %>
    
    <br>
</div>

app/views/simple_pages/thank_you.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <p>Thank you. We have received your message and will respond as soon as possible.</p>
  </div><!-- / panel-body -->
</div><!-- / panel -->